baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Quickstart'
theme = "ananke"
[params]
    subtitle = "Following the Hugo documentation's quickstart guide"
    [params.contact]
    email = "dont@me.dude"
    phone = "+1 000-000-0000"
